# NUMPY

<b>1. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.<b>

In [41]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,5]])

In [42]:
print(f"Size: {arr1.size}")
print(f"Sum: {arr1.sum()}")
print(f"Length: {arr1.itemsize}")
print(f"Total bytes: {arr1.nbytes}")

Size: 6
Sum: 18
Length: 4
Total bytes: 24


<b>2. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.<b>    

In [51]:
set1={1,2,3,4,5,6,7,8,9,10}
set2={10,8,6,4,2}

In [52]:
set1-set2

{1, 3, 5, 7, 9}

<b>3. Write a NumPy program to compute the cross product of two given vectors.<b>

In [54]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [56]:
arr_cp=np.cross(arr1,arr2)

In [57]:
arr_cp

array([-3,  6, -3])

<b>4. Write a NumPy program to compute the determinant of a given square array.<b>

In [64]:
import numpy as np
arr1=([1,2,3])
arr2=([3,4,5])
arr3=([6,7,8])

In [65]:
cons_arr=np.array([arr1,arr2,arr3])
arr_det=np.linalg.det(cons_arr)

In [66]:
arr_det

-3.7007434154172e-17

<b>5. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.<b>

In [67]:
import numpy as np
arr1=([1,2])
arr2=([3,4])


In [68]:
arr_eigval=np.linalg.eigvals([arr1,arr2])

In [69]:
arr_eigval

array([-0.37228132,  5.37228132])

In [70]:
np.linalg.eig([arr1,arr2])

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

<b>6. Write a NumPy program to multiple three matrices each of 3*3 dimension.<b>

In [77]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
arr3=np.array([6,7,8])

In [78]:
arr_mul=np.matmul(arr1,arr2,arr3)

In [79]:
arr_mul

array([26,  7,  8])

<b>7. Explore the Linear Algebra support provided by NumPy.<b>

In [80]:
# 10 cofee + 12 tea = Rs. 52
# 21 cofee + 30 tea = Rs. 103

In [85]:
import numpy as np
arr1 = np.array([[10,12],[21,30]])
arr2 = np.array([52,103])
cost = np.linalg.solve(arr1,arr2)

In [86]:
cost

array([ 6.75      , -1.29166667])